apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-finalizer-controller
  namespace: payments
  labels:
    app.kubernetes.io/name: payment-finalizer-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-finalizer-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment-finalizer-controller
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: payment-finalizer-controller
      containers:
        - name: controller
          image: payment-finalizer-controller:local
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POLL_SECONDS
              value: "3"
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
      securityContext:
        seccompProfile:
          type: RuntimeDefault
