apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-api
  namespace: payments
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: risk-api
  namespace: payments
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ledger-api
  namespace: payments
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mesh-client
  namespace: payments
